spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


paypal.return-url=${PAYPAL_SUCCESS_URL}
paypal.cancel-url=${PAYPAL_CANCEL_URL}

